version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
